source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/fanfanqy/SelfGithubSpec.git'
use_frameworks!

platform :ios, '10.0'

target 'JQQYBase_Example' do
  pod 'JQQYBase', :path => '../'

  target 'JQQYBase_Tests' do
    inherit! :search_paths

    
  end
end
